// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ws.proto

package ws

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//rpc request
type ServeRequest struct {
	RequestId            string   `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	UniqId               int64    `protobuf:"varint,2,opt,name=uniq_id,json=uniqId,proto3" json:"uniq_id,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServeRequest) Reset()         { *m = ServeRequest{} }
func (m *ServeRequest) String() string { return proto.CompactTextString(m) }
func (*ServeRequest) ProtoMessage()    {}
func (*ServeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ff87931dac4ca82, []int{0}
}

func (m *ServeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServeRequest.Unmarshal(m, b)
}
func (m *ServeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServeRequest.Marshal(b, m, deterministic)
}
func (m *ServeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServeRequest.Merge(m, src)
}
func (m *ServeRequest) XXX_Size() int {
	return xxx_messageInfo_ServeRequest.Size(m)
}
func (m *ServeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ServeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ServeRequest proto.InternalMessageInfo

func (m *ServeRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *ServeRequest) GetUniqId() int64 {
	if m != nil {
		return m.UniqId
	}
	return 0
}

func (m *ServeRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

//rpc response
type ServeReply struct {
	RequestId            string   `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ErrCode              int32    `protobuf:"varint,2,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServeReply) Reset()         { *m = ServeReply{} }
func (m *ServeReply) String() string { return proto.CompactTextString(m) }
func (*ServeReply) ProtoMessage()    {}
func (*ServeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ff87931dac4ca82, []int{1}
}

func (m *ServeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServeReply.Unmarshal(m, b)
}
func (m *ServeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServeReply.Marshal(b, m, deterministic)
}
func (m *ServeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServeReply.Merge(m, src)
}
func (m *ServeReply) XXX_Size() int {
	return xxx_messageInfo_ServeReply.Size(m)
}
func (m *ServeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ServeReply.DiscardUnknown(m)
}

var xxx_messageInfo_ServeReply proto.InternalMessageInfo

func (m *ServeReply) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *ServeReply) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *ServeReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*ServeRequest)(nil), "ws.ServeRequest")
	proto.RegisterType((*ServeReply)(nil), "ws.ServeReply")
}

func init() { proto.RegisterFile("ws.proto", fileDescriptor_7ff87931dac4ca82) }

var fileDescriptor_7ff87931dac4ca82 = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x28, 0x2f, 0xd6, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x2f, 0x56, 0x8a, 0xe2, 0xe2, 0x09, 0x4e, 0x2d, 0x2a,
	0x4b, 0x0d, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x92, 0xe5, 0xe2, 0x2a, 0x82, 0x30, 0xe3,
	0x33, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x38, 0xa1, 0x22, 0x9e, 0x29, 0x42, 0xe2,
	0x5c, 0xec, 0xa5, 0x79, 0x99, 0x85, 0x20, 0x39, 0x26, 0x05, 0x46, 0x0d, 0xe6, 0x20, 0x36, 0x10,
	0xd7, 0x33, 0x45, 0x48, 0x88, 0x8b, 0x25, 0x25, 0xb1, 0x24, 0x51, 0x82, 0x59, 0x81, 0x51, 0x83,
	0x27, 0x08, 0xcc, 0x56, 0x4a, 0xe0, 0xe2, 0x82, 0x9a, 0x5d, 0x90, 0x53, 0x49, 0xc8, 0x64, 0x49,
	0x2e, 0x8e, 0xd4, 0xa2, 0xa2, 0xf8, 0xe4, 0xfc, 0x94, 0x54, 0xb0, 0xd1, 0xac, 0x41, 0xec, 0xa9,
	0x45, 0x45, 0xce, 0xf9, 0x29, 0xa9, 0x42, 0x12, 0x5c, 0xec, 0xb9, 0xa9, 0xc5, 0xc5, 0x89, 0xe9,
	0xa9, 0x60, 0xe3, 0x39, 0x83, 0x60, 0x5c, 0x23, 0x33, 0x2e, 0xd6, 0xf0, 0xe2, 0xa0, 0x82, 0x64,
	0x21, 0x5d, 0x2e, 0xf6, 0x80, 0xd2, 0xa4, 0x9c, 0xcc, 0xe2, 0x0c, 0x21, 0x01, 0xbd, 0xf2, 0x62,
	0x3d, 0x64, 0x3f, 0x49, 0xf1, 0x21, 0x89, 0x14, 0xe4, 0x54, 0x2a, 0x31, 0x24, 0xb1, 0x81, 0x03,
	0xc0, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xd9, 0xad, 0x15, 0x1b, 0x0c, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WsRpcClient is the client API for WsRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WsRpcClient interface {
	Publish(ctx context.Context, in *ServeRequest, opts ...grpc.CallOption) (*ServeReply, error)
}

type wsRpcClient struct {
	cc *grpc.ClientConn
}

func NewWsRpcClient(cc *grpc.ClientConn) WsRpcClient {
	return &wsRpcClient{cc}
}

func (c *wsRpcClient) Publish(ctx context.Context, in *ServeRequest, opts ...grpc.CallOption) (*ServeReply, error) {
	out := new(ServeReply)
	err := c.cc.Invoke(ctx, "/ws.WsRpc/Publish", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WsRpcServer is the server API for WsRpc service.
type WsRpcServer interface {
	Publish(context.Context, *ServeRequest) (*ServeReply, error)
}

// UnimplementedWsRpcServer can be embedded to have forward compatible implementations.
type UnimplementedWsRpcServer struct {
}

func (*UnimplementedWsRpcServer) Publish(ctx context.Context, req *ServeRequest) (*ServeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Publish not implemented")
}

func RegisterWsRpcServer(s *grpc.Server, srv WsRpcServer) {
	s.RegisterService(&_WsRpc_serviceDesc, srv)
}

func _WsRpc_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WsRpcServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ws.WsRpc/Publish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WsRpcServer).Publish(ctx, req.(*ServeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WsRpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ws.WsRpc",
	HandlerType: (*WsRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Publish",
			Handler:    _WsRpc_Publish_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ws.proto",
}
