// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hub.proto

package hub

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//ws request
type WsRequest struct {
	RequestId            string   `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	FromId               int64    `protobuf:"varint,2,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WsRequest) Reset()         { *m = WsRequest{} }
func (m *WsRequest) String() string { return proto.CompactTextString(m) }
func (*WsRequest) ProtoMessage()    {}
func (*WsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3103f8d3056b01c, []int{0}
}

func (m *WsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WsRequest.Unmarshal(m, b)
}
func (m *WsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WsRequest.Marshal(b, m, deterministic)
}
func (m *WsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WsRequest.Merge(m, src)
}
func (m *WsRequest) XXX_Size() int {
	return xxx_messageInfo_WsRequest.Size(m)
}
func (m *WsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WsRequest proto.InternalMessageInfo

func (m *WsRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *WsRequest) GetFromId() int64 {
	if m != nil {
		return m.FromId
	}
	return 0
}

func (m *WsRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

//ws response
type HubReply struct {
	RequestId            string   `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ErrCode              int32    `protobuf:"varint,2,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HubReply) Reset()         { *m = HubReply{} }
func (m *HubReply) String() string { return proto.CompactTextString(m) }
func (*HubReply) ProtoMessage()    {}
func (*HubReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3103f8d3056b01c, []int{1}
}

func (m *HubReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HubReply.Unmarshal(m, b)
}
func (m *HubReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HubReply.Marshal(b, m, deterministic)
}
func (m *HubReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HubReply.Merge(m, src)
}
func (m *HubReply) XXX_Size() int {
	return xxx_messageInfo_HubReply.Size(m)
}
func (m *HubReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HubReply.DiscardUnknown(m)
}

var xxx_messageInfo_HubReply proto.InternalMessageInfo

func (m *HubReply) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *HubReply) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *HubReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

//app request
type AppRequest struct {
	RequestId            string   `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ToId                 int64    `protobuf:"varint,2,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppRequest) Reset()         { *m = AppRequest{} }
func (m *AppRequest) String() string { return proto.CompactTextString(m) }
func (*AppRequest) ProtoMessage()    {}
func (*AppRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3103f8d3056b01c, []int{2}
}

func (m *AppRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppRequest.Unmarshal(m, b)
}
func (m *AppRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppRequest.Marshal(b, m, deterministic)
}
func (m *AppRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppRequest.Merge(m, src)
}
func (m *AppRequest) XXX_Size() int {
	return xxx_messageInfo_AppRequest.Size(m)
}
func (m *AppRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AppRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AppRequest proto.InternalMessageInfo

func (m *AppRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *AppRequest) GetToId() int64 {
	if m != nil {
		return m.ToId
	}
	return 0
}

func (m *AppRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*WsRequest)(nil), "hub.WsRequest")
	proto.RegisterType((*HubReply)(nil), "hub.HubReply")
	proto.RegisterType((*AppRequest)(nil), "hub.AppRequest")
}

func init() { proto.RegisterFile("hub.proto", fileDescriptor_b3103f8d3056b01c) }

var fileDescriptor_b3103f8d3056b01c = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x4f, 0x4b, 0x03, 0x31,
	0x10, 0xc5, 0x5d, 0xb7, 0xed, 0x36, 0xa3, 0x55, 0x18, 0x0f, 0xae, 0x82, 0xb0, 0xec, 0x69, 0x4f,
	0x55, 0xf4, 0x13, 0xd4, 0x7a, 0x68, 0xaf, 0x51, 0xd8, 0x9b, 0x25, 0x31, 0xa3, 0x15, 0xec, 0x26,
	0xe6, 0x0f, 0xd2, 0x6f, 0x2f, 0x89, 0xd6, 0x1e, 0x14, 0xec, 0x6d, 0x5e, 0x86, 0xf7, 0xf8, 0xe5,
	0x0d, 0xb0, 0x65, 0x90, 0x63, 0x63, 0xb5, 0xd7, 0x98, 0x2f, 0x83, 0xac, 0x5b, 0x60, 0xad, 0xe3,
	0xf4, 0x1e, 0xc8, 0x79, 0xbc, 0x00, 0xb0, 0x5f, 0xe3, 0xe2, 0x55, 0x95, 0x59, 0x95, 0x35, 0x8c,
	0xb3, 0xef, 0x97, 0xb9, 0xc2, 0x53, 0x28, 0x9e, 0xad, 0x5e, 0xc5, 0xdd, 0x7e, 0x95, 0x35, 0x39,
	0x1f, 0x44, 0x39, 0x57, 0x88, 0xd0, 0x53, 0xc2, 0x8b, 0x32, 0xaf, 0xb2, 0xe6, 0x90, 0xa7, 0xb9,
	0x7e, 0x84, 0xe1, 0x2c, 0x48, 0x4e, 0xe6, 0x6d, 0xfd, 0x5f, 0xee, 0x19, 0x0c, 0xc9, 0xda, 0xc5,
	0x93, 0x56, 0x94, 0x82, 0xfb, 0xbc, 0x20, 0x6b, 0xa7, 0x5a, 0x11, 0x96, 0x50, 0xac, 0xc8, 0x39,
	0xf1, 0x42, 0x29, 0x9c, 0xf1, 0x8d, 0xac, 0x1f, 0x00, 0x26, 0xc6, 0xec, 0x48, 0x7e, 0x02, 0x7d,
	0xaf, 0xb7, 0xdc, 0x3d, 0xaf, 0xff, 0xa6, 0xbe, 0xee, 0x80, 0xcd, 0x82, 0x9c, 0x52, 0xe7, 0xc9,
	0xe2, 0x15, 0x8c, 0xee, 0xa9, 0x53, 0xad, 0xe3, 0xe2, 0xe3, 0x76, 0xed, 0x09, 0x8f, 0xc6, 0xb1,
	0xbd, 0x9f, 0xbe, 0xce, 0x47, 0x49, 0x6f, 0xbe, 0x59, 0xef, 0xe1, 0x25, 0x1c, 0x44, 0xc7, 0xc4,
	0x98, 0x3b, 0xe1, 0x05, 0x1e, 0xa7, 0xfd, 0x16, 0xf3, 0x97, 0x41, 0x0e, 0xd2, 0x29, 0x6e, 0x3e,
	0x03, 0x00, 0x00, 0xff, 0xff, 0x70, 0x2a, 0xd3, 0xc2, 0x97, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HubCenterClient is the client API for HubCenter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HubCenterClient interface {
	SendWsRawByte(ctx context.Context, in *WsRequest, opts ...grpc.CallOption) (*HubReply, error)
	SendAppData(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*HubReply, error)
}

type hubCenterClient struct {
	cc *grpc.ClientConn
}

func NewHubCenterClient(cc *grpc.ClientConn) HubCenterClient {
	return &hubCenterClient{cc}
}

func (c *hubCenterClient) SendWsRawByte(ctx context.Context, in *WsRequest, opts ...grpc.CallOption) (*HubReply, error) {
	out := new(HubReply)
	err := c.cc.Invoke(ctx, "/hub.HubCenter/SendWsRawByte", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubCenterClient) SendAppData(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*HubReply, error) {
	out := new(HubReply)
	err := c.cc.Invoke(ctx, "/hub.HubCenter/SendAppData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HubCenterServer is the server API for HubCenter service.
type HubCenterServer interface {
	SendWsRawByte(context.Context, *WsRequest) (*HubReply, error)
	SendAppData(context.Context, *AppRequest) (*HubReply, error)
}

// UnimplementedHubCenterServer can be embedded to have forward compatible implementations.
type UnimplementedHubCenterServer struct {
}

func (*UnimplementedHubCenterServer) SendWsRawByte(ctx context.Context, req *WsRequest) (*HubReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendWsRawByte not implemented")
}
func (*UnimplementedHubCenterServer) SendAppData(ctx context.Context, req *AppRequest) (*HubReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendAppData not implemented")
}

func RegisterHubCenterServer(s *grpc.Server, srv HubCenterServer) {
	s.RegisterService(&_HubCenter_serviceDesc, srv)
}

func _HubCenter_SendWsRawByte_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubCenterServer).SendWsRawByte(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hub.HubCenter/SendWsRawByte",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubCenterServer).SendWsRawByte(ctx, req.(*WsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubCenter_SendAppData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubCenterServer).SendAppData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hub.HubCenter/SendAppData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubCenterServer).SendAppData(ctx, req.(*AppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HubCenter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hub.HubCenter",
	HandlerType: (*HubCenterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendWsRawByte",
			Handler:    _HubCenter_SendWsRawByte_Handler,
		},
		{
			MethodName: "SendAppData",
			Handler:    _HubCenter_SendAppData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hub.proto",
}
